var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/responsable/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__024iggd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0knlbee._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0cf5w5p.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~03_f8._.js")
R.c("server/chunks/ssr/node_modules_12pcxnx._.js")
R.c("server/chunks/ssr/_0k_99zv._.js")
R.c("server/chunks/ssr/app_error_tsx_11t4ysq._.js")
R.c("server/chunks/ssr/app_loading_tsx_05semg5._.js")
R.c("server/chunks/ssr/app_not-found_tsx_0u.hoe4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_responsable_page_actions_0s_5z6j.js")
R.m(196104)
module.exports=R.m(196104).exports
