// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agents">> = Specific
  const handler = {} as typeof import("../../app/admin/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/diplomes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/diplomes">> = Specific
  const handler = {} as typeof import("../../app/admin/diplomes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/groups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/groups">> = Specific
  const handler = {} as typeof import("../../app/admin/groups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/integrations">> = Specific
  const handler = {} as typeof import("../../app/admin/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/knowledge-bases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/knowledge-bases">> = Specific
  const handler = {} as typeof import("../../app/admin/knowledge-bases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/routing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/routing">> = Specific
  const handler = {} as typeof import("../../app/admin/routing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/sources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sources">> = Specific
  const handler = {} as typeof import("../../app/admin/sources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/workflows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/workflows">> = Specific
  const handler = {} as typeof import("../../app/admin/workflows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents">> = Specific
  const handler = {} as typeof import("../../app/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/docs/ui/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api/docs/ui">> = Specific
  const handler = {} as typeof import("../../app/api/docs/ui/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/apropos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apropos">> = Specific
  const handler = {} as typeof import("../../app/apropos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/c/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/c/[id]">> = Specific
  const handler = {} as typeof import("../../app/c/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/legal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal">> = Specific
  const handler = {} as typeof import("../../app/legal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/responsable/[groupId]/members/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/responsable/[groupId]/members">> = Specific
  const handler = {} as typeof import("../../app/responsable/[groupId]/members/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/responsable/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/responsable">> = Specific
  const handler = {} as typeof import("../../app/responsable/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/session/[code]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/session/[code]">> = Specific
  const handler = {} as typeof import("../../app/session/[code]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sessions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sessions/[id]">> = Specific
  const handler = {} as typeof import("../../app/sessions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sessions/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sessions/new">> = Specific
  const handler = {} as typeof import("../../app/sessions/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sessions">> = Specific
  const handler = {} as typeof import("../../app/sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/spaces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/spaces">> = Specific
  const handler = {} as typeof import("../../app/spaces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/agents/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/agents/[slug]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/agents/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/agents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/agents">> = Specific
  const handler = {} as typeof import("../../app/api/admin/agents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/alerts">> = Specific
  const handler = {} as typeof import("../../app/api/admin/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/diplomes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/diplomes/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/diplomes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/diplomes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/diplomes">> = Specific
  const handler = {} as typeof import("../../app/api/admin/diplomes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/groups/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/groups/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/groups/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/groups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/groups">> = Specific
  const handler = {} as typeof import("../../app/api/admin/groups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/hil/contacts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/hil/contacts">> = Specific
  const handler = {} as typeof import("../../app/api/admin/hil/contacts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/hil/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/hil">> = Specific
  const handler = {} as typeof import("../../app/api/admin/hil/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/indexing-queue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/indexing-queue">> = Specific
  const handler = {} as typeof import("../../app/api/admin/indexing-queue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/integrations/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/integrations/[slug]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/integrations/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/integrations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/integrations">> = Specific
  const handler = {} as typeof import("../../app/api/admin/integrations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/knowledge-bases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/knowledge-bases">> = Specific
  const handler = {} as typeof import("../../app/api/admin/knowledge-bases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/meta-prompts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/meta-prompts">> = Specific
  const handler = {} as typeof import("../../app/api/admin/meta-prompts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/metrics/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/metrics/export">> = Specific
  const handler = {} as typeof import("../../app/api/admin/metrics/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/metrics">> = Specific
  const handler = {} as typeof import("../../app/api/admin/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/routing/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/routing/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/routing/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/routing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/routing">> = Specific
  const handler = {} as typeof import("../../app/api/admin/routing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/sources/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/sources/[slug]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/sources/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/sources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/sources">> = Specific
  const handler = {} as typeof import("../../app/api/admin/sources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/webhook/dify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/webhook/dify">> = Specific
  const handler = {} as typeof import("../../app/api/admin/webhook/dify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/workflows/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/workflows">> = Specific
  const handler = {} as typeof import("../../app/api/admin/workflows/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents">> = Specific
  const handler = {} as typeof import("../../app/api/agents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/config/agents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/config/agents">> = Specific
  const handler = {} as typeof import("../../app/api/config/agents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/config/sources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/config/sources">> = Specific
  const handler = {} as typeof import("../../app/api/config/sources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/connectors/gdrive/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connectors/gdrive/callback">> = Specific
  const handler = {} as typeof import("../../app/api/connectors/gdrive/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/connectors/gdrive/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connectors/gdrive/connect">> = Specific
  const handler = {} as typeof import("../../app/api/connectors/gdrive/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/connectors/gdrive/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connectors/gdrive/files">> = Specific
  const handler = {} as typeof import("../../app/api/connectors/gdrive/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/connectors/gdrive/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connectors/gdrive/import">> = Specific
  const handler = {} as typeof import("../../app/api/connectors/gdrive/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/connectors/gdrive/init/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connectors/gdrive/init">> = Specific
  const handler = {} as typeof import("../../app/api/connectors/gdrive/init/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/connectors/notion/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connectors/notion/connect">> = Specific
  const handler = {} as typeof import("../../app/api/connectors/notion/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/connectors/notion/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connectors/notion/import">> = Specific
  const handler = {} as typeof import("../../app/api/connectors/notion/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/connectors/notion/pages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connectors/notion/pages">> = Specific
  const handler = {} as typeof import("../../app/api/connectors/notion/pages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/conversations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/conversations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/conversations/all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations/all">> = Specific
  const handler = {} as typeof import("../../app/api/conversations/all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations">> = Specific
  const handler = {} as typeof import("../../app/api/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/docs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/docs">> = Specific
  const handler = {} as typeof import("../../app/api/docs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/hil/contacts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hil/contacts">> = Specific
  const handler = {} as typeof import("../../app/api/hil/contacts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/hil/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hil/request">> = Specific
  const handler = {} as typeof import("../../app/api/hil/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/hil/requests/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hil/requests/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/hil/requests/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/hil/requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hil/requests">> = Specific
  const handler = {} as typeof import("../../app/api/hil/requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/sources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/sources">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/sources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/[id]/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/[id]/feedback">> = Specific
  const handler = {} as typeof import("../../app/api/messages/[id]/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/meta-prompts/[id]/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta-prompts/[id]/activate">> = Specific
  const handler = {} as typeof import("../../app/api/meta-prompts/[id]/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/meta-prompts/[id]/duplicate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta-prompts/[id]/duplicate">> = Specific
  const handler = {} as typeof import("../../app/api/meta-prompts/[id]/duplicate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/meta-prompts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta-prompts/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/meta-prompts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/meta-prompts/active/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta-prompts/active">> = Specific
  const handler = {} as typeof import("../../app/api/meta-prompts/active/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/meta-prompts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meta-prompts">> = Specific
  const handler = {} as typeof import("../../app/api/meta-prompts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/complete">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/quota/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quota">> = Specific
  const handler = {} as typeof import("../../app/api/quota/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/report">> = Specific
  const handler = {} as typeof import("../../app/api/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/responsable/[groupId]/csv-import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/responsable/[groupId]/csv-import">> = Specific
  const handler = {} as typeof import("../../app/api/responsable/[groupId]/csv-import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/responsable/[groupId]/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/responsable/[groupId]/members">> = Specific
  const handler = {} as typeof import("../../app/api/responsable/[groupId]/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/responsable/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/responsable/audit">> = Specific
  const handler = {} as typeof import("../../app/api/responsable/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/responsable/groups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/responsable/groups">> = Specific
  const handler = {} as typeof import("../../app/api/responsable/groups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/routing/families/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/routing/families">> = Specific
  const handler = {} as typeof import("../../app/api/routing/families/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/routing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/routing">> = Specific
  const handler = {} as typeof import("../../app/api/routing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/session/[code]/guest-chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/session/[code]/guest-chat">> = Specific
  const handler = {} as typeof import("../../app/api/session/[code]/guest-chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/session/[code]/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/session/[code]/join">> = Specific
  const handler = {} as typeof import("../../app/api/session/[code]/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/session/[code]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/session/[code]">> = Specific
  const handler = {} as typeof import("../../app/api/session/[code]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[id]/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[id]/analytics">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[id]/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[id]/broadcast/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[id]/broadcast">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[id]/broadcast/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sessions/scenarios/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sessions/scenarios">> = Specific
  const handler = {} as typeof import("../../app/api/sessions/scenarios/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sources">> = Specific
  const handler = {} as typeof import("../../app/api/sources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spaces/[id]/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spaces/[id]/audit">> = Specific
  const handler = {} as typeof import("../../app/api/spaces/[id]/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spaces/[id]/documents/[docId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spaces/[id]/documents/[docId]">> = Specific
  const handler = {} as typeof import("../../app/api/spaces/[id]/documents/[docId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spaces/[id]/documents/[docId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spaces/[id]/documents/[docId]/status">> = Specific
  const handler = {} as typeof import("../../app/api/spaces/[id]/documents/[docId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spaces/[id]/documents/[docId]/visibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spaces/[id]/documents/[docId]/visibility">> = Specific
  const handler = {} as typeof import("../../app/api/spaces/[id]/documents/[docId]/visibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spaces/[id]/documents/batch-visibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spaces/[id]/documents/batch-visibility">> = Specific
  const handler = {} as typeof import("../../app/api/spaces/[id]/documents/batch-visibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spaces/[id]/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spaces/[id]/documents">> = Specific
  const handler = {} as typeof import("../../app/api/spaces/[id]/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spaces/[id]/folders/[folderId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spaces/[id]/folders/[folderId]">> = Specific
  const handler = {} as typeof import("../../app/api/spaces/[id]/folders/[folderId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spaces/[id]/folders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spaces/[id]/folders">> = Specific
  const handler = {} as typeof import("../../app/api/spaces/[id]/folders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spaces/[id]/members/count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spaces/[id]/members/count">> = Specific
  const handler = {} as typeof import("../../app/api/spaces/[id]/members/count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spaces/[id]/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spaces/[id]/members">> = Specific
  const handler = {} as typeof import("../../app/api/spaces/[id]/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spaces/[id]/members/users/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spaces/[id]/members/users/search">> = Specific
  const handler = {} as typeof import("../../app/api/spaces/[id]/members/users/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spaces/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spaces/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/spaces/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spaces/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spaces">> = Specific
  const handler = {} as typeof import("../../app/api/spaces/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/spaces/shared/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spaces/shared">> = Specific
  const handler = {} as typeof import("../../app/api/spaces/shared/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/surveys/[id]/respond/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/surveys/[id]/respond">> = Specific
  const handler = {} as typeof import("../../app/api/surveys/[id]/respond/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/surveys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/surveys">> = Specific
  const handler = {} as typeof import("../../app/api/surveys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/usage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/usage">> = Specific
  const handler = {} as typeof import("../../app/api/usage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/account">> = Specific
  const handler = {} as typeof import("../../app/api/user/account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/user/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/export">> = Specific
  const handler = {} as typeof import("../../app/api/user/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/password">> = Specific
  const handler = {} as typeof import("../../app/api/users/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/profile">> = Specific
  const handler = {} as typeof import("../../app/api/users/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
