var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/spaces/[id]/documents/route.js")
R.c("server/chunks/[root-of-the-server]__08_2az2._.js")
R.c("server/chunks/_0igl5ks._.js")
R.c("server/chunks/_05s1~d~._.js")
R.c("server/chunks/[root-of-the-server]__02vtwn7._.js")
R.c("server/chunks/node_modules_zod_v4_0l4wk-v._.js")
R.c("server/chunks/[root-of-the-server]__0an_phr._.js")
R.c("server/chunks/_next-internal_server_app_api_spaces_[id]_documents_route_actions_13l40as.js")
R.m(889605)
module.exports=R.m(889605).exports
