var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/sessions/route.js")
R.c("server/chunks/[externals]__0bkm31i._.js")
R.c("server/chunks/_0igl5ks._.js")
R.c("server/chunks/_05s1~d~._.js")
R.c("server/chunks/node_modules_zod_v4_0ogk55_._.js")
R.c("server/chunks/[root-of-the-server]__02vtwn7._.js")
R.c("server/chunks/_0vqsvkj._.js")
R.c("server/chunks/_next-internal_server_app_api_sessions_route_actions_0y1t9w0.js")
R.m(395764)
module.exports=R.m(395764).exports
